export const metadata = {
    title: "Authentication",
    description: "Generated by Next.js",
  };
  
  export default function AuthenticationLayout({
    children,
  }: {
    children: React.ReactNode;
  }) {
    return <div lang="en">{children}</div>;
  }
  