import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { Providers } from "../../provider/ReduxProovider";
import  SessionProviderWrapper  from "../../provider/SessionProvider"; 

const Font = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HR Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Font.className}>
        <SessionProviderWrapper>
          <Providers>
            {children}
          </Providers>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
