import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";
import { Providers } from "../../provider/ReduxProovider";
import SessionProviderWrapper from "../../provider/SessionProvider";
import { Toaster } from "react-hot-toast";
import { DarkProvider } from "../../provider/DarkModeProvider";

const Font = Lexend({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HR Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Font.className}>
        <SessionProviderWrapper>
          <Toaster />
          <Providers>
            <DarkProvider>{children}</DarkProvider>
          </Providers>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
